# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='backend.Problem'),
            preserve_default=False,
        ),
    ]
