# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170708_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
