# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170708_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('ECONOMY', 'Economy'), ('EDUCATION', 'Education'), ('MEDIA', 'Media'), ('COMMUNITY', 'Community'), ('ENVIRONMENT', 'Environment')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
