# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_problem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('ECONOMY', 'Economy'), ('EDUCATION', 'Education'), ('MEDIA', 'Media'), ('COMMUNITY', 'Community'), ('ENVIRONMENT', 'Environment')], default='HEALTH', max_length=255),
        ),
    ]
